FROM node:20-bullseye-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --no-audit --no-fund
COPY next.config.mjs tsconfig.json ./
COPY app ./app
COPY src ./src
COPY components ./components
EXPOSE 3000
CMD ["npm","run","dev"]
