FROM node:20-bullseye-slim
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --no-audit --no-fund
COPY tsconfig.json ./tsconfig.json
COPY src ./src
EXPOSE 8081
CMD ["npm","run","dev"]
